# Generated by Django 5.2.11 on 2026-02-24 16:38

import codeforlife.models.fields.encrypted_text
import codeforlife.user.models.user.admin_school_teacher
import codeforlife.user.models.user.contactable
import codeforlife.user.models.user.google
import codeforlife.user.models.user.independent
import codeforlife.user.models.user.non_admin_school_teacher
import codeforlife.user.models.user.non_school_teacher
import codeforlife.user.models.user.school_teacher
import codeforlife.user.models.user.student
import codeforlife.user.models.user.teacher
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("access_code", models.CharField(max_length=5, null=True)),
                ("classmates_data_viewable", models.BooleanField(default=False)),
                ("always_accept_requests", models.BooleanField(default=False)),
                ("accept_requests_until", models.DateTimeField(null=True)),
                (
                    "creation_time",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "classes",
            },
        ),
        migrations.CreateModel(
            name="DailyActivity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("csv_click_count", models.PositiveIntegerField(default=0)),
                ("login_cards_click_count", models.PositiveIntegerField(default=0)),
                (
                    "primary_coding_club_downloads",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "python_coding_club_downloads",
                    models.PositiveIntegerField(default=0),
                ),
                ("level_control_submits", models.PositiveBigIntegerField(default=0)),
                ("teacher_lockout_resets", models.PositiveIntegerField(default=0)),
                ("indy_lockout_resets", models.PositiveIntegerField(default=0)),
                (
                    "school_student_lockout_resets",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "anonymised_unverified_teachers",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "anonymised_unverified_independents",
                    models.PositiveIntegerField(default=0),
                ),
            ],
            options={
                "verbose_name_plural": "Daily activities",
            },
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                (
                    "country",
                    django_countries.fields.CountryField(
                        blank=True, max_length=2, null=True
                    ),
                ),
                ("county", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "creation_time",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="TotalActivity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("teacher_registrations", models.PositiveIntegerField(default=0)),
                ("student_registrations", models.PositiveIntegerField(default=0)),
                ("independent_registrations", models.PositiveIntegerField(default=0)),
                (
                    "anonymised_unverified_teachers",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "anonymised_unverified_independents",
                    models.PositiveIntegerField(default=0),
                ),
            ],
            options={
                "verbose_name_plural": "Total activity",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="ContactableUser",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("user.user",),
            managers=[
                (
                    "objects",
                    codeforlife.user.models.user.contactable.ContactableUserManager(),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentUser",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("user.user",),
            managers=[
                ("objects", codeforlife.user.models.user.student.StudentUserManager()),
            ],
        ),
        migrations.CreateModel(
            name="AuthFactor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.TextField(choices=[("otp", "one-time password")])),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auth_factors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "type")},
            },
        ),
        migrations.CreateModel(
            name="OtpBypassToken",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    codeforlife.models.fields.encrypted_text.EncryptedTextField(
                        associated_data="token",
                        db_column="token",
                        default=None,
                        help_text="The encrypted equivalent of the token.",
                        verbose_name="token",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="otp_bypass_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "OTP bypass token",
                "verbose_name_plural": "OTP bypass tokens",
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "session_key",
                    models.CharField(
                        max_length=40,
                        primary_key=True,
                        serialize=False,
                        verbose_name="session key",
                    ),
                ),
                ("session_data", models.TextField(verbose_name="session data")),
                (
                    "expire_date",
                    models.DateTimeField(db_index=True, verbose_name="expire date"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "session",
                "verbose_name_plural": "sessions",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("login_id", models.CharField(max_length=64, null=True)),
                ("blocked_time", models.DateTimeField(blank=True, null=True)),
                (
                    "class_field",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="user.class",
                    ),
                ),
                (
                    "new_user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="new_student",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pending_class_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="class_request",
                        to="user.class",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JoinReleaseStudent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action_type", models.CharField(max_length=64)),
                (
                    "action_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student",
                        to="user.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Independent",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("user.student",),
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_admin", models.BooleanField(default=False)),
                ("blocked_time", models.DateTimeField(blank=True, null=True)),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invited_teachers",
                        to="user.teacher",
                    ),
                ),
                (
                    "new_user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="new_teacher",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="teacher_school",
                        to="user.school",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SchoolTeacherInvitation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=88)),
                ("invited_teacher_first_name", models.CharField(max_length=150)),
                ("invited_teacher_last_name", models.CharField(max_length=150)),
                ("invited_teacher_email", models.EmailField(max_length=254)),
                ("invited_teacher_is_admin", models.BooleanField(default=False)),
                ("expiry", models.DateTimeField()),
                (
                    "creation_time",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "school",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="teacher_invitations",
                        to="user.school",
                    ),
                ),
                (
                    "from_teacher",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="school_invitations",
                        to="user.teacher",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="class",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_classes",
                to="user.teacher",
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="class_teacher",
                to="user.teacher",
            ),
        ),
        migrations.CreateModel(
            name="NonSchoolTeacher",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("user.teacher",),
        ),
        migrations.CreateModel(
            name="SchoolTeacher",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("user.teacher",),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("otp_secret", models.CharField(blank=True, max_length=40, null=True)),
                ("last_otp_for_time", models.DateTimeField(blank=True, null=True)),
                ("developer", models.BooleanField(default=False)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="teacher",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="user.userprofile"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="user.userprofile"
            ),
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("login_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("login_type", models.CharField(max_length=100, null=True)),
                (
                    "class_field",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="user.class",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="user.school",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GoogleUser",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("user.contactableuser",),
            managers=[
                ("objects", codeforlife.user.models.user.google.GoogleUserManager()),
            ],
        ),
        migrations.CreateModel(
            name="IndependentUser",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("user.contactableuser",),
            managers=[
                (
                    "objects",
                    codeforlife.user.models.user.independent.IndependentUserManager(),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeacherUser",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("user.contactableuser",),
            managers=[
                ("objects", codeforlife.user.models.user.teacher.TeacherUserManager()),
            ],
        ),
        migrations.CreateModel(
            name="SessionAuthFactor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "auth_factor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="user.authfactor",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auth_factors",
                        to="user.session",
                    ),
                ),
            ],
            options={
                "unique_together": {("session", "auth_factor")},
            },
        ),
        migrations.CreateModel(
            name="AdminSchoolTeacher",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("user.schoolteacher",),
        ),
        migrations.CreateModel(
            name="NonAdminSchoolTeacher",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("user.schoolteacher",),
        ),
        migrations.AddConstraint(
            model_name="teacher",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_admin", True), ("school__isnull", True), _negated=True
                ),
                name="teacher__is_admin",
            ),
        ),
        migrations.CreateModel(
            name="NonSchoolTeacherUser",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("user.teacheruser",),
            managers=[
                (
                    "objects",
                    codeforlife.user.models.user.non_school_teacher.NonSchoolTeacherUserManager(),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SchoolTeacherUser",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("user.teacheruser",),
            managers=[
                (
                    "objects",
                    codeforlife.user.models.user.school_teacher.SchoolTeacherUserManager(),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdminSchoolTeacherUser",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("user.schoolteacheruser",),
            managers=[
                (
                    "objects",
                    codeforlife.user.models.user.admin_school_teacher.AdminSchoolTeacherUserManager(),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NonAdminSchoolTeacherUser",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("user.schoolteacheruser",),
            managers=[
                (
                    "objects",
                    codeforlife.user.models.user.non_admin_school_teacher.NonAdminSchoolTeacherUserManager(),
                ),
            ],
        ),
    ]
