# Generated by Django 5.2.11 on 2026-02-24 14:18

import codeforlife.models.fields.data_encryption_key
import codeforlife.user.models.user.user
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", codeforlife.user.models.user.user.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name="school",
            name="dek",
            field=codeforlife.models.fields.data_encryption_key.DataEncryptionKeyField(
                editable=False,
                help_text="The encrypted data encryption key (DEK) for this model.",
                null=True,
                verbose_name="data encryption key",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="dek",
            field=codeforlife.models.fields.data_encryption_key.DataEncryptionKeyField(
                editable=False,
                help_text="The encrypted data encryption key (DEK) for this model.",
                null=True,
                verbose_name="data encryption key",
            ),
        ),
    ]
