# Generated by Django 3.2.23 on 2024-02-08 14:57

import codeforlife.user.models.user
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0048_unique_school_names'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndependentUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user.user',),
            managers=[
                ('objects', codeforlife.user.models.user.IndependentUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='NonSchoolTeacher',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('common.teacher',),
        ),
        migrations.CreateModel(
            name='NonSchoolTeacherUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user.user',),
            managers=[
                ('objects', codeforlife.user.models.user.NonSchoolTeacherUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SchoolTeacher',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('common.teacher',),
        ),
        migrations.CreateModel(
            name='SchoolTeacherUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user.user',),
            managers=[
                ('objects', codeforlife.user.models.user.SchoolTeacherUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='StudentUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user.user',),
            managers=[
                ('objects', codeforlife.user.models.user.StudentUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='TeacherUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user.user',),
            managers=[
                ('objects', codeforlife.user.models.user.TeacherUserManager()),
            ],
        ),
    ]
